name: Test CI

on: 
  pull_request:
  push:
    paths:
      - lua/**
      - test/**
      - .github/**

jobs:
  test:
    runs-on:   ubuntu-latest
    container: alpine

    steps:
    - uses: actions/checkout@v4

    - name: Install requirements
      run: |
        apk update && apk upgrade
        apk add make bash coreutils neovim lua5.4

    - name: Install Tangerine
      run:  make install

    - name: Build Runner
      run:  make runner

    - name: Run Tests
      run:  yes | make test
